{% set name = "aiomysql" %}
{% set version = "0.0.17" %}
{% set sha256 = "85a8e00ab9a1ed53b58e90d228c5539775aabcbe338dfc32d75a97ca54aca0e9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vvv"

requirements:
  build:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pymysql >=0.7.5

test:
  imports:
    - aiomysql

about:
  home: https://github.com/aio-libs/aiomysql
  summary: "aiomysql is a library for accessing a MySQL database from the asyncio"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
