{% set name = "aiomysql" %}
{% set version = "0.0.13" %}
{% set sha256 = "f12b7634acc672efc639f8e2d8516e3c6d50747264f0d94ab5a456e9baf1c864" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py<33]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - asyncio  # [py<34]
    - pymysql >=0.7.5

test:
  imports:
    - aiomysql

about:
  home: https://github.com/aio-libs/aiomysql
  summary: "aiomysql is a library for accessing a MySQL database from the asyncio"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kszucs
