appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: fl7KdfaKgEPracVmMa2BPo68yWfNDKdI+j0kegKtL8LCDV4ZY+UpziqlJHaQ9IpkIIcMfcG8I5Pk69eKwFp1+7eP1/leMSincPGiT7o+g6n52xun6cp/zSuHnJJQZzrzRuknuN6A/O1vKeR9qxRSIofUBotoe3YrRc9ZNEIM48hJDbkcJg47LWQgblqCTr0J3XFBVQQi/5cuA8pHenBvS6+T9coKiwRX2EB3wGWtjjRcta23bcb35fd2v/Xz4om7IMwty6ojKGqh1r9i9YGXvxImRwiG5NXph5GYR1ZquYN1+KZL7gVoSZXJ4cCC48vmlJpRs7zbuLSREsmkrHjcgeE8W4+09/GBoRwL9O1rWfp04fCWTX6zxEIRNzE5lseZa5eiWDnQaYG4LQlCHJlyGWGoCm5EfP3jr7/FV7tiPmde2gCYp5NUy945LsVJaaRxAacubXl3kA11i0leTTEd20JAeoLL3MuxXVc3MWRjUhYIofJKsd1sfLg95y2/xUwFDq69Q2oSsSI4rfVQuYX00xC05Wiksi/F1erIq+YVpKU+sbceaDQtfuM+OVHMB74c0SLPZjKVHswHE9JrqzSrfPDwBwhvMBkDF1ACyCB5B55zM3ALyLmHHW6WddxBFJZaNVTby7ba/xDXInsecSBzzs65h9CihHQPPBKhw2tdI2A=}
